[pytest]
addopts =
    -ra
    --import-mode=importlib
    --cov-config=.coveragerc
    --cov-context=test
    --cov-report=
    --mypy-ini-file=tests/mypy/pytest_mypy.ini
    --mypy-only-local-stub
    # TODO: This is needed to include the mypy plugin in coverage. However the docs say:
    # TODO  "Useful for debugging, will create problems with import cache" - better solution?
    --mypy-same-process

testpaths = tests
python_files = *_test.py *Test.py
python_classes = *Test

# Fail on warnings
filterwarnings = error
