[tox]
requires = tox >= 4.32
envlist = clean, py3{10-14}, report, flake8, mypy
skip_missing_interpreters = true

[flake8]
max-line-length = 120
exclude = _version.py
ignore =
    # "Line break occurred before a binary operator" (see https://www.flake8rules.com/rules/W503.html)
    W503

[testenv]
# Build and install a wheel (speeds up tox runs)
package = wheel
wheel_build_env = .pkg

# Install all testing requirements by default(pytest, mypy etc.)
extras = testing

# Default command: Run pytest
commands = python -m pytest --cov --cov-append {posargs}

[testenv:pytest-mypy]
# Run only the typing tests with pytest
commands = python -m pytest {posargs:tests/mypy}

[testenv:flake8]
commands = flake8 src/ tests/

[testenv:mypy,py3{10-14}-mypy]
commands = mypy {posargs}

[testenv:mypy-debug]
# Use no-incremental to disable mypy caching when developing the mypy plugin
commands = mypy --show-traceback --no-incremental {posargs}

[testenv:clean]
commands = coverage erase

[testenv:report,py3{10-14}-report]
commands =
    coverage html
    coverage report --fail-under=100
