"""
validataclass
Copyright (c) 2021, binary butterfly GmbH and contributors
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file.
"""

import dataclasses
import warnings
from typing import Any

from typing_extensions import TypeVar, deprecated, overload

from validataclass.validators import Validator
from .defaults import BaseDefault, Default, NoDefault, _NoDefaultType

__all__ = [
    'validataclass_field',
]

T_Validated = TypeVar('T_Validated')
T_Default = TypeVar('T_Default')


# NOTE: Actual return type of this function is `Field[T_Validated | T_Default]`. However, we will pretend here that it
# returns `T_Validated | T_Default` instead, to help type checkers understand what happens within the context of a
# dataclass. This is the same thing that typeshed does.
# (Using this function outside the context of a dataclass usually doesn't make a lot of sense.)

@overload
def validataclass_field(
    validator: Validator[T_Validated],
    *,
    default: _NoDefaultType = NoDefault,
    metadata: dict[str, Any] | None = None,
    **kwargs: Any,
) -> T_Validated:
    ...


@overload
def validataclass_field(
    validator: Validator[T_Validated],
    *,
    default: BaseDefault[T_Default],
    metadata: dict[str, Any] | None = None,
    **kwargs: Any,
) -> T_Validated | T_Default:
    ...


@overload
@deprecated('Use default objects instead of raw defaults or dataclasses.MISSING')
def validataclass_field(
    validator: Validator[T_Validated],
    *,
    default: Any,
    metadata: dict[str, Any] | None = None,
    **kwargs: Any,
) -> Any:
    ...


def validataclass_field(
    validator: Validator[T_Validated],
    *,
    default: BaseDefault[T_Default] | Any = NoDefault,
    metadata: dict[str, Any] | None = None,
    **kwargs: Any,
) -> Any:
    """
    Defines a dataclass field compatible with DataclassValidator.

    Wraps the regular `dataclasses.field()` function, but has special parameters to add validator metadata to the field.

    Additional keyword arguments will be passed to `dataclasses.field()`, with some exceptions:

    - `default` is handled by this function to set metadata. It must be a validataclass default object (e.g. an instance
      of `Default` or `DefaultFactory`, or the special value `NoDefault`). Using raw default values is **deprecated**
      and won't be supported in the future. The same applies to the `dataclasses.MISSING` sentinel.
    - `default_factory` is not allowed. Use `default=DefaultFactory(...)` instead.
    - `init` is not allowed. To create a non-init field, use `dataclasses.field(init=False)` instead.

    Parameters:
        `validator`: Validator to use for validating the field (subclass of `Validator`).
        `default`: Default value when the field is missing (subclass of `BaseDefault`, defaults to `NoDefault`).
        `metadata`: Base dictionary for field metadata, gets merged with the metadata generated by this function.
        `**kwargs`: Additional keyword arguments that are passed to `dataclasses.field()`.
    """
    # If metadata is specified as argument, use it as the base for the field's metadata
    if metadata is None:
        metadata = {}

    # Check for incompatible keyword arguments
    if 'init' in kwargs:
        raise ValueError('Keyword argument "init" is not allowed in validataclass_field.')
    if 'default_factory' in kwargs:
        raise ValueError(
            'Keyword argument "default_factory" is not allowed in validataclass_field (use default=DefaultFactory(...) '
            'instead).'
        )

    # Add validator metadata
    metadata['validator'] = validator

    # Ensure default is a validataclass default object (any subclass of BaseDefault)
    # TODO: Remove deprecated behaviour for raw defaults and dataclasses.MISSING in a future version.
    if default is dataclasses.MISSING:
        warnings.warn(
            'Using validataclass_field() with `default=dataclasses.MISSING` is deprecated. '
            'Please use `default=NoDefault` instead.',
            DeprecationWarning
        )
        default = NoDefault
    elif not isinstance(default, BaseDefault):
        # Wrap value in a validataclass default object
        warnings.warn(
            'Using validataclass_field() with raw default values is deprecated. '
            'Please use default objects instead (e.g. `default=Default(...)`).',
            DeprecationWarning
        )
        default = Default(default)

    if default is not NoDefault:
        # Add default values to metadata
        metadata['validator_default'] = default

        # Set regular dataclass default or default_factory
        if default.needs_factory():
            kwargs['default_factory'] = lambda: default.get_value()
        else:
            kwargs['default'] = default.get_value()

    # Create a dataclass field with our metadata
    return dataclasses.field(metadata=metadata, **kwargs)
