"""
validataclass
Copyright (c) 2021, binary butterfly GmbH and contributors
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file.
"""

import dataclasses
from typing import Any

from validataclass.validators import Validator
from .defaults import BaseDefault, Default, NoDefault

__all__ = [
    'validataclass_field',
]


def validataclass_field(
    validator: Validator[Any],
    *,
    default: Any = NoDefault,
    metadata: dict[str, Any] | None = None,
    **kwargs: Any,
) -> Any:
    """
    Defines a dataclass field compatible with DataclassValidator.

    Wraps the regular `dataclasses.field()` function, but has special parameters to add validator metadata to the field.

    Additional keyword arguments will be passed to `dataclasses.field()`, with some exceptions:

    - `default` is handled by this function to set metadata. It can be either a direct value or a validataclass default
      object, i.e. an object of a subclass of `BaseDefault` (e.g. `Default`, `DefaultFactory`, `NoDefault`).
      It is then converted to a direct value (or factory) if necessary and passed to `dataclasses.field()`.
    - `default_factory` is not allowed. Use `default=DefaultFactory(...)` instead.
    - `init` is not allowed. To create a non-init field, use `dataclasses.field(init=False)` instead.

    Parameters:
        `validator`: Validator to use for validating the field (subclass of `Validator`).
        `default`: Default value when the field is missing in the input data (any value or subclass of `BaseDefault`).
        `metadata`: Base dictionary for field metadata, gets merged with the metadata generated by this function.
        `**kwargs`: Additional keyword arguments that are passed to `dataclasses.field()`.
    """
    # If metadata is specified as argument, use it as the base for the field's metadata
    if metadata is None:
        metadata = {}

    # Check for incompatible keyword arguments
    if 'init' in kwargs:
        raise ValueError('Keyword argument "init" is not allowed in validator field.')
    if 'default_factory' in kwargs:
        raise ValueError(
            'Keyword argument "default_factory" is not allowed in validator field (use default=DefaultFactory(...) '
            'instead).'
        )

    # Add validator metadata
    metadata['validator'] = validator

    # Ensure default is a validataclass default object (any subclass of BaseDefault)
    if default is dataclasses.MISSING:
        default = NoDefault
    elif not isinstance(default, BaseDefault):
        # Wrap value in a validataclass default object
        default = Default(default)

    if default is not NoDefault:
        # Add default values to metadata
        metadata['validator_default'] = default

        # Set regular dataclass default or default_factory
        if default.needs_factory():
            kwargs['default_factory'] = lambda: default.get_value()
        else:
            kwargs['default'] = default.get_value()

    # Create a dataclass field with our metadata
    return dataclasses.field(metadata=metadata, **kwargs)
